### ISSUE TITLE
MA cert has no uuid, email

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-ch#107]
When you run various scripts using the MA cert, it does not have a UID or email in the subjectAltName. Various scripts that try to retrieve it will fail.

EG:
```
12/02/2013 14:48:08:ERROR   :amsoil:[logv1] [SERVER] SERVER_ERROR ((DataError) invalid input syntax for uuid: "None"
LINE 1: ..., message) VALUES (E'2013-12-02 19:48:08.782521', E'None', E...
                                                             ^
 'INSERT INTO logging_entry (event_time, user_id, message) VALUES (%(event_time)s, %(user_id)s, %(message)s) RETURNING logging_entry
.id' {'message': u'Changed member Pam Helinek to role ADMIN in project projectb', 'user_id': 'None', 'event_time': '2013-12-02 19:48
:08.782521'})
12/02/2013 14:48:08:ERROR   :amsoil:[logv1] Traceback (most recent call last):
  File "/usr/share/geni-ch/chapi/AMsoil-gpo-0.3.2/src/plugins/logging/Logging.py", line 53, in log_event
    attributes, user_id)
  File "/usr/share/geni-ch/chapi/AMsoil-gpo-0.3.2/src/plugins/logging/Logging.py", line 136, in log_event
    result = session.execute(ins)
  File "/usr/local/lib/python2.6/dist-packages/sqlalchemy/orm/session.py", line 934, in execute
    clause, params or {})
  File "/usr/local/lib/python2.6/dist-packages/sqlalchemy/engine/base.py", line 662, in execute
    params)
  File "/usr/local/lib/python2.6/dist-packages/sqlalchemy/engine/base.py", line 761, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/local/lib/python2.6/dist-packages/sqlalchemy/engine/base.py", line 874, in _execute_context
    context)
  File "/usr/local/lib/python2.6/dist-packages/sqlalchemy/engine/base.py", line 1024, in _handle_dbapi_exception
    exc_info
  File "/usr/local/lib/python2.6/dist-packages/sqlalchemy/util/compat.py", line 196, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/usr/local/lib/python2.6/dist-packages/sqlalchemy/engine/base.py", line 867, in _execute_context
    context)
  File "/usr/local/lib/python2.6/dist-packages/sqlalchemy/engine/default.py", line 324, in do_execute
    cursor.execute(statement, parameters)
DataError: (DataError) invalid input syntax for uuid: "None"
LINE 1: ..., message) VALUES (E'2013-12-02 19:48:08.782521', E'None', E...
```

This is in the SA, modify_project_membership has a None client_uuid in the call to modify_membership. It gets that using:
```
        client_uuid = get_uuid_from_cert(client_cert)
```

 _Imported from trac ticket [#107](http://trac.gpolab.bbn.com/chapi/ticket/107),  created by ahelsing on 12-02-2013 at 15:47, last modified: 12-03-2013 at 11:59_

**Comment by ahelsing** [comment]
This is really a couple things.

First, our MA cert has the UID in a malformed entry that our cert utils can't find.

Second, all sorts of spots in the code assume we have a UID and produce SQL errors if we don't.


_Trac comment by ahelsing on 12-02-2013 at 16:45_

**Comment by ahelsing** [comment]
With changes that let me get the UID from the MA cert and that avoid doing things if I don't have the client_uuid, I get errors where something is doing lookup_identifying_member_info trying to get a pretty name for the MA using the UID from the MA cert. That fails in lookup_member_info when it can't find any attributes for that UID.
I get this reliably when I do "Edit Project Membership".  I think I have multiple messages where the logger was the MA, which means the portal has to call lookup_member_names with the MA UID.

I then get errors from project.php like this:
```
[Mon Dec 02 22:46:15 2013] [error] [client 128.89.254.135] PHP Notice:  Undefined index: 0b2c83d3-369b-4d4e-bb1d-6f5bd1affb4c in /var/www/secure/project.php on line 331, referer: https://portal-ah.gpolab.bbn.com/secure/edit-project-member.php?project_id=2f91f41e-fd0f-4cb8-893a-354075920ab3
```

Now what?

_Trac comment by ahelsing on 12-02-2013 at 22:54_

**Comment by ahelsing** [comment]
The old ma_client returned NONE as the name for unknown members (like the MA). So I need to make this one do the same.


_Trac comment by ahelsing on 12-03-2013 at 11:59_
