### ISSUE TITLE
SQLAlchemy cursor already closed

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-ch#117]
From chapi.log:
```
12/03/2013 15:35:58:INFO    :chapi:SA: johren@bbn.com: Created slice jotest in project 516c5660-6483-4022-8fb1-c1ff8ce392e6
12/03/2013 15:42:03:WARNING :sqlalchemy.pool.QueuePool:Error closing cursor: cursor already closed
12/03/2013 15:42:03:ERROR   :chapi:CS: nriga@bbn.com: Exception: (ProgrammingError) SSL error: EVP lib
 'SELECT cs_action.name AS cs_action_name, cs_action.context_type AS cs_action_context_type, sa_slice_member.slice_id AS context \nFROM cs_action, sa_slice_member, cs_policy \nWHERE sa_slice_member.member_id = %(member_id_1)s AND sa_slice_member.role = cs_policy.attribute AND cs_action.privilege = cs_policy.privilege AND cs_policy.context_type = %(context_type_1)s AND cs_action.context_type = cs_policy.context_type' {'member_id_1': 'ef70241d-ab79-4577-8b4f-ea523935f17a', 'context_type_1': 2}
  File "/usr/share/geni-ch/chapi/AMsoil-gpo-0.3.2/src/plugins/csrm/CredentialStore.py", line 95, in get_permissions
    credentials, options)
  File "/usr/share/geni-ch/chapi/AMsoil-gpo-0.3.2/src/plugins/csrm/CredentialStore.py", line 195, in get_permissions
    slice_rows = q.all()
  File "/usr/local/lib/python2.6/dist-packages/sqlalchemy/orm/query.py", line 2241, in all
    return list(self)
...
```

 _Imported from trac ticket [#117](http://trac.gpolab.bbn.com/chapi/ticket/117),  created by ahelsing on 12-03-2013 at 15:55, last modified: 12-12-2013 at 15:40_

**Comment by ahelsing** [comment]
The postrgres log shows:
```
2013-12-03 15:42:03 EST LOG:  could not send data to client: Broken pipe
2013-12-03 15:42:03 EST STATEMENT:  SELECT cs_action.name AS cs_action_name, cs_action.context_type AS cs_action_context_type, sa_slice_member.slice_id AS context 
	FROM cs_action, sa_slice_member, cs_policy 
	WHERE sa_slice_member.member_id = E'ef70241d-ab79-4577-8b4f-ea523935f17a' AND sa_slice_member.role = cs_policy.attribute AND cs_action.privilege = cs_policy.privilege AND cs_policy.context_type = 2 AND cs_action.context_type = cs_policy.context_type
2013-12-03 15:42:03 EST LOG:  SSL error: bad write retry
2013-12-03 15:42:03 EST LOG:  could not send data to client: Connection reset by peer
2013-12-03 15:42:03 EST LOG:  could not receive data from client: Connection reset by peer
2013-12-03 15:42:03 EST LOG:  unexpected EOF on client connection
```


_Trac comment by ahelsing on 12-03-2013 at 16:57_

**Comment by ahelsing** [comment]
The full chapi error log:
```
12/03/2013 15:42:03:WARNING :sqlalchemy.pool.QueuePool:Error closing cursor: cursor already closed
12/03/2013 15:42:03:ERROR   :chapi:CS: nriga@bbn.com: Exception: (ProgrammingError) SSL error: EVP lib
 'SELECT cs_action.name AS cs_action_name, cs_action.context_type AS cs_action_context_type, sa_slice_member.slice_id AS context \nFROM cs_action, sa_slice_member, cs_policy \nWHERE sa_slice_member.member_id = %(member_id_1)s AND sa_slice_member.role = cs_policy.attribute AND cs_action.privilege = cs_policy.privilege AND cs_policy.context_type = %(context_type_1)s AND cs_action.context_type = cs_policy.context_type' {'member_id_1': 'ef70241d-ab79-4577-8b4f-ea523935f17a', 'context_type_1': 2}
  File "/usr/share/geni-ch/chapi/AMsoil-gpo-0.3.2/src/plugins/csrm/CredentialStore.py", line 95, in get_permissions
    credentials, options)
  File "/usr/share/geni-ch/chapi/AMsoil-gpo-0.3.2/src/plugins/csrm/CredentialStore.py", line 195, in get_permissions
    slice_rows = q.all()
  File "/usr/local/lib/python2.6/dist-packages/sqlalchemy/orm/query.py", line 2241, in all
    return list(self)
  File "/usr/local/lib/python2.6/dist-packages/sqlalchemy/orm/query.py", line 2353, in __iter__
    return self._execute_and_instances(context)
  File "/usr/local/lib/python2.6/dist-packages/sqlalchemy/orm/query.py", line 2368, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/usr/local/lib/python2.6/dist-packages/sqlalchemy/engine/base.py", line 662, in execute
    params)
  File "/usr/local/lib/python2.6/dist-packages/sqlalchemy/engine/base.py", line 761, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/local/lib/python2.6/dist-packages/sqlalchemy/engine/base.py", line 874, in _execute_context
    context)
  File "/usr/local/lib/python2.6/dist-packages/sqlalchemy/engine/base.py", line 1024, in _handle_dbapi_exception
    exc_info
  File "/usr/local/lib/python2.6/dist-packages/sqlalchemy/util/compat.py", line 196, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/usr/local/lib/python2.6/dist-packages/sqlalchemy/engine/base.py", line 867, in _execute_context
    context)
  File "/usr/local/lib/python2.6/dist-packages/sqlalchemy/engine/default.py", line 324, in do_execute
    cursor.execute(statement, parameters)

12/03/2013 15:42:03:ERROR   :amsoil:[csv1] [SERVER] SERVER_ERROR ((ProgrammingError) SSL error: EVP lib
 'SELECT cs_action.name AS cs_action_name, cs_action.context_type AS cs_action_context_type, sa_slice_member.slice_id AS context \nFROM cs_action, sa_slice_member, cs_policy \nWHERE sa_slice_member.member_id = %(member_id_1)s AND sa_slice_member.role = cs_policy.attribute AND cs_action.privilege = cs_policy.privilege AND cs_policy.context_type = %(context_type_1)s AND cs_action.context_type = cs_policy.context_type' {'member_id_1': 'ef70241d-ab79-4577-8b4f-ea523935f17a', 'context_type_1': 2})
12/03/2013 15:42:03:ERROR   :amsoil:[csv1] Traceback (most recent call last):
  File "/usr/share/geni-ch/chapi/AMsoil-gpo-0.3.2/src/plugins/csrm/CredentialStore.py", line 95, in get_permissions
    credentials, options)
  File "/usr/share/geni-ch/chapi/AMsoil-gpo-0.3.2/src/plugins/csrm/CredentialStore.py", line 195, in get_permissions
    slice_rows = q.all()
  File "/usr/local/lib/python2.6/dist-packages/sqlalchemy/orm/query.py", line 2241, in all
    return list(self)
  File "/usr/local/lib/python2.6/dist-packages/sqlalchemy/orm/query.py", line 2353, in __iter__
    return self._execute_and_instances(context)
  File "/usr/local/lib/python2.6/dist-packages/sqlalchemy/orm/query.py", line 2368, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/usr/local/lib/python2.6/dist-packages/sqlalchemy/engine/base.py", line 662, in execute
    params)
  File "/usr/local/lib/python2.6/dist-packages/sqlalchemy/engine/base.py", line 761, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/local/lib/python2.6/dist-packages/sqlalchemy/engine/base.py", line 874, in _execute_context
    context)
  File "/usr/local/lib/python2.6/dist-packages/sqlalchemy/engine/base.py", line 1024, in _handle_dbapi_exception
    exc_info
  File "/usr/local/lib/python2.6/dist-packages/sqlalchemy/util/compat.py", line 196, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/usr/local/lib/python2.6/dist-packages/sqlalchemy/engine/base.py", line 867, in _execute_context
    context)
  File "/usr/local/lib/python2.6/dist-packages/sqlalchemy/engine/default.py", line 324, in do_execute
    cursor.execute(statement, parameters)
ProgrammingError: (ProgrammingError) SSL error: EVP lib
 'SELECT cs_action.name AS cs_action_name, cs_action.context_type AS cs_action_context_type, sa_slice_member.slice_id AS context \nFROM cs_action, sa_slice_member, cs_policy \nWHERE sa_slice_member.member_id = %(member_id_1)s AND sa_slice_member.role = cs_policy.attribute AND cs_action.privilege = cs_policy.privilege AND cs_policy.context_type = %(context_type_1)s AND cs_action.context_type = cs_policy.context_type' {'member_id_1': 'ef70241d-ab79-4577-8b4f-ea523935f17a', 'context_type_1': 2}
```


_Trac comment by ahelsing on 12-03-2013 at 16:59_

**Comment by ahelsing** [comment]
Maybe we need to enable keepalives in postgres?

http://stackoverflow.com/questions/6592137/sqlalchemy-fails-to-connect-to-db-after-server-is-idle-for-a-few-hours

(The change is in /etc/postgresql/8.4/main/postgresql.conf)

This documentation may be relevant:
http://docs.sqlalchemy.org/en/rel_0_8/core/pooling.html#dealing-with-disconnects

Maybe a connection in the pool was closed when we went to use it?

Looking at the SQLAlchemy code: The message about the cursor was already closed is when SQLAlchemy was handling that ProgrammingError: It first tries to safely close the cursor, catching and logging any exception.

The ProgrammingError "Wraps a DB-API ProgrammingError"

The SSL EVP library is part of openssl: https://www.openssl.org/docs/crypto/evp.html

Sounds to me like an SSL error broke the low level driver connection to the DB, and this manifests itself in this way.

Perhaps this is related to ticket #48 ?

FWIW: We are using python2.6-psycopg2 that works only with python2.6 and SQLAlchemy 0.8.3, which supposedly works well with that driver the default for postgres) and that database.

_Trac comment by ahelsing on 12-04-2013 at 10:25_

**Comment by ahelsing** [comment]
Here is a thread about a possibly related error. Here it suggests that if your application uses OpenSSL for other things, then that can cause some weird problems with getting SSL error codes. In particular, a connection can fail because it sees an error message for the previous user of OpenSSL.

http://www.postgresql.org/message-id/20121126225957GG4227@alvh.no-ip.org

That just suggests that something else might have had an error using openssl - it doesn't tell us who had the error or what it was, or what to do about it. So in some ways, it just muddies the waters. It might not be our fault.


_Trac comment by ahelsing on 12-04-2013 at 10:36_

**Comment by ahelsing** [comment]
Nothing actionable here, but keep the ticket open if we see it again or figure out how to reproduce it.

_Trac comment by ahelsing on 12-04-2013 at 16:31_

**Comment by ahelsing** [comment]
I revoked my operator privileges, went to the list of expired projects, and clicked on the project lead (Niky) and got the following error:

[SERVER] SERVER_ERROR ((ProgrammingError) SSL error EVP lib 'SELECT sa_slice.id AS sa_slice_id, sa_slice.slice_id AS sa_slice_slice_id, sa_slice.owner_id AS sa_slice_owner_id, sa_slice.project_id AS sa_slice_project_id, sa_slice.creation AS sa_slice_creation, sa_slice.expiration AS sa_slice_expiration, sa_slice.expired AS sa_slice_expired, sa_slice.slice_name AS sa_slice_slice_name, sa_slice.slice_urn AS sa_slice_slice_urn, sa_slice.slice_email AS sa_slice_slice_email, sa_slice.certificate AS sa_slice_certificate, sa_slice.slice_description AS sa_slice_slice_description, pa_project.project_id AS pa_project_project_id, pa_project.project_name AS >pa_project_project_name \nFROM sa_slice, pa_project \nWHERE sa_slice.project_id = pa_project.project_id AND sa_slice.project_id = %(project_id_1)s' {'project_id_1': '383be941-56ae-42bb-b945-fb1c714fe197'})

From chapi.log:
12/04/2013 17:27:21:INFO    :chapi:SA: phelinek@bbn.com: Invoked lookup_slices Options {'match': {'_GENI_PROJECT_UID': '383be941-5\
6ae-42bb-b945-fb1c714fe197'}} Arguments {}
12/04/2013 17:27:21:WARNING :sqlalchemy.pool.QueuePool:Error closing cursor: cursor already closed
12/04/2013 17:27:21:ERROR   :chapi:SA: phelinek@bbn.com: Exception: (ProgrammingError) SSL error: EVP lib
 'SELECT sa_slice.id AS sa_slice_id, sa_slice.slice_id AS sa_slice_slice_id, sa_slice.owner_id AS sa_slice_owner_id, sa_slice.proj\
ect_id AS sa_slice_project_id, sa_slice.creation AS sa_slice_creation, sa_slice.expiration AS sa_slice_expiration, sa_slice.expire\
d AS sa_slice_expired, sa_slice.slice_name AS sa_slice_slice_name, sa_slice.slice_urn AS sa_slice_slice_urn, sa_slice.slice_email \
AS sa_slice_slice_email, sa_slice.certificate AS sa_slice_certificate, sa_slice.slice_description AS sa_slice_slice_description, p\
a_project.project_id AS pa_project_project_id, pa_project.project_name AS pa_project_project_name \nFROM sa_slice, pa_project \nWH\
ERE sa_slice.project_id = pa_project.project_id AND sa_slice.project_id = %(project_id_1)s' {'project_id_1': '383be941-56ae-42bb-b\
945-fb1c714fe197'}
  File "/usr/share/geni-ch/chapi/AMsoil-gpo-0.3.2/src/plugins/chapiv1rpc/chapi/SliceAuthority.py", line 92, in lookup_slices
    results = self._delegate.lookup_slices(client_cert, credentials, options)
  File "/usr/share/geni-ch/chapi/AMsoil-gpo-0.3.2/src/plugins/sarm/SAv1PersistentImplementation.py", line 218, in lookup_slices
    rows = q.all()
  File "/usr/local/lib/python2.6/dist-packages/sqlalchemy/orm/query.py", line 2241, in all
    return list(self)
  File "/usr/local/lib/python2.6/dist-packages/sqlalchemy/orm/query.py", line 2353, in __iter__
    return self._execute_and_instances(context)
  File "/usr/local/lib/python2.6/dist-packages/sqlalchemy/orm/query.py", line 2368, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/usr/local/lib/python2.6/dist-packages/sqlalchemy/engine/base.py", line 662, in execute
    params)
  File "/usr/local/lib/python2.6/dist-packages/sqlalchemy/engine/base.py", line 761, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/local/lib/python2.6/dist-packages/sqlalchemy/engine/base.py", line 761, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/local/lib/python2.6/dist-packages/sqlalchemy/engine/base.py", line 874, in _execute_context
    context)
  File "/usr/local/lib/python2.6/dist-packages/sqlalchemy/engine/base.py", line 1024, in _handle_dbapi_exception
    exc_info
  File "/usr/local/lib/python2.6/dist-packages/sqlalchemy/util/compat.py", line 196, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/usr/local/lib/python2.6/dist-packages/sqlalchemy/engine/base.py", line 867, in _execute_context
    context)
  File "/usr/local/lib/python2.6/dist-packages/sqlalchemy/engine/default.py", line 324, in do_execute
    cursor.execute(statement, parameters)

12/04/2013 17:27:21:ERROR   :amsoil:[sav1] [SERVER] SERVER_ERROR ((ProgrammingError) SSL error: EVP lib

_Trac comment by phelinek on 12-04-2013 at 17:38_

**Comment by ahelsing** [comment]
Note that Pam's instance of the error was a different query in a different AMsoil plugin. Both occur when SQLalchemy tried to do cursor.execute.

This suggests that it is not something in our code, but in the chain from SQLalchemy through pycopg2 driver to postgres via openssl.


_Trac comment by ahelsing on 12-05-2013 at 08:37_

**Comment by ahelsing** [comment]
Could we make the base handlers/delegates explicitly try to catch SQLAlchemy programming errors with a description that says ssl evp lib? And then perhaps retry the function? Or at least give the experimenter a more friendly error message?

_Trac comment by ahelsing on 12-05-2013 at 08:39_

**Comment by ahelsing** [comment]
Some thoughts
 - It seems to usually be Niky - is size of query relevant?
 - Is there some session hygiene we aren't doing? Like 2 nested open sessions?
 - Is there some earlier exception that causes this later?
 - It seems to be a "q.all" that causes this - maybe we should read 100 records at a time at most?

_Trac comment by ahelsing on 12-05-2013 at 09:10_

**Comment by ahelsing** [comment]
On Friday we changed the postgres configuration to not use SSL.

We have not seen the error since then.


_Trac comment by ahelsing on 12-09-2013 at 09:28_

**Comment by MarshallBrinn** [comment]
Checked in fix for uniform handling of sessions: a given method should open at most one session with a commit/rollback at the end. See MethodContext.py.

_Trac comment by mbrinn (github user: MarshallBrinn) on 12-12-2013 at 15:40_
