### ISSUE TITLE
Niky can't connect to PGCH

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-ch#197]
When Niky tries any connection to PGCH it fails:
```
Python: CPython 2.7.4
OS: Darwin-11.4.2-x86_64-i386-64bit
...
14:47:14 ERROR    omni.pgch: Call for GetVersion of GENI Clearinghouse CH https://ch.geni.net:8443/ using cert /Users/inki/.ssl/geni_cert_portal.pem failed.: Unknown SSL error [Errno 8] _ssl.c:504: EOF occurred in violation of protocol
14:47:14 DEBUG    omni.pgch: Traceback (most recent call last):
  File "/usr/local/bin/gcf-2.4/src/omnilib/util/dossl.py", line 69, in _do_ssl
    result = fn(*args)
  File "/usr/local/Cellar/python/2.7.4/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xmlrpclib.py", line 1224, in __call__
    return self.__send(self.__name, args)
  File "/usr/local/Cellar/python/2.7.4/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xmlrpclib.py", line 1578, in __request
    verbose=self.__verbose
  File "/usr/local/Cellar/python/2.7.4/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xmlrpclib.py", line 1264, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/local/Cellar/python/2.7.4/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xmlrpclib.py", line 1292, in single_request
    self.send_content(h, request_body)
  File "/usr/local/Cellar/python/2.7.4/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xmlrpclib.py", line 1439, in send_content
    connection.endheaders(request_body)
  File "/usr/local/Cellar/python/2.7.4/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 969, in endheaders
    self._send_output(message_body)
  File "/usr/local/Cellar/python/2.7.4/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 829, in _send_output
    self.send(msg)
  File "/usr/local/Cellar/python/2.7.4/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 791, in send
    self.connect()
  File "/usr/local/Cellar/python/2.7.4/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1176, in connect
    self.sock = ssl.wrap_socket(sock, self.key_file, self.cert_file)
  File "/usr/local/Cellar/python/2.7.4/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py", line 383, in wrap_socket
    ciphers=ciphers)
  File "/usr/local/Cellar/python/2.7.4/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py", line 143, in __init__
    self.do_handshake()
  File "/usr/local/Cellar/python/2.7.4/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py", line 305, in do_handshake
    self._sslobj.do_handshake()
SSLError: [Errno 8] _ssl.c:504: EOF occurred in violation of protocol
```

Telnet to ch.geni.net works.

But openssl does not:
```
$  openssl s_client -connect ch.geni.net:8443
CONNECTED(00000003)
depth=2 /C=US/O=GeoTrust Inc./CN=GeoTrust Global CA
verify error:num=20:unable to get local issuer certificate
verify return:0
4397:error:140790E5:SSL routines:SSL23_WRITE:ssl handshake failure:/SourceCache/OpenSSL098/OpenSSL098-49.1/src/ssl/s23_lib.c:182:
```

This is her in the access logs:
```
192.1.17.220 - - [18/Dec/2013:14:44:52 -0500] "-" 408 3857 "-" "-"
```

Is this a firewall issue? A python version issue? Something to do with her version of openssl? I see people complaining about those kinds of things when getting these errors. Sometimes it is fixed by specifying you want TLSv1 as the protocol. But that did not help Niky through openssl s_client.

 _Imported from trac ticket [#197](http://trac.gpolab.bbn.com/chapi/ticket/197),  created by ahelsing on 12-18-2013 at 15:07, last modified: 01-07-2014 at 08:39_
   CCing: sedwards@...

**Comment by ahelsing** [comment]
openssl with -debug ends with:
```
000c - <SPACES/NULS>
write to 0x10f9194d0 [0x7fc50381c000] (139 bytes => 139 (0x8B))
0000 - 16 03 01 00 86 10 00 00-82 00 80 5d 70 fe cd 06   ...........]p...
0010 - 1a ae a3 05 57 0c b6 42-d4 a3 14 ef e2 18 f4 3e   ....W..B.......>
0020 - 7f 6f 6e c3 20 ed 95 e9-ca 37 54 45 9d a6 6d df   .on. ....7TE..m.
0030 - 01 ab 43 13 eb 18 9b e1-01 61 2f a1 af fb 32 86   ..C......a/...2.
0040 - 3c be 41 d8 fc 89 2d fa-62 31 05 69 88 cd 22 48   <.A...-.b1.i.."H
0050 - 09 1c 61 ec b9 2a a1 a4-49 c9 ac e3 30 e4 94 f2   ..a..*..I...0...
0060 - 64 c7 f9 1b 76 02 a8 c6-2f 91 68 0f 1e 90 07 ff   d...v.../.h.....
0070 - 61 07 ac 9a 5b 11 c9 5e-14 0b 0c 2e c7 fd b9 c9   a...[0080 - 28 88 57 38 b8 5c 2e e0-26 4f 4e                  (.W8.\..&ON
write to 0x10f9194d0 [0x7fc50381c000](..^........) (6 bytes => 6 (0x6))
0000 - 14 03 01 00 01 01                                 ......
write to 0x10f9194d0 [0x7fc50381c000] (53 bytes => 53 (0x35))
0000 - 16 03 01 00 30 95 ce 19-4a a8 0f 67 97 d2 98 a4   ....0...J..g....
0010 - 86 a8 40 39 16 96 7b 73-ef e6 3c ad c4 8f 97 74   ..@9..{s..<....t
0020 - c6 74 30 e1 df 9c 30 a9-61 43 aa 93 98 50 64 0d   .t0...0.aC...Pd.
0030 - 9d eb 65 a6 cf                                    ..e..
read from 0x10f9194d0 [0x7fc503811c00] (5 bytes => 0 (0x0))
4412:error:1409E0E5:SSL routines:SSL3_WRITE_BYTES:ssl handshake failure:/SourceCache/OpenSSL098/OpenSSL098-49.1/src/ssl/s3_pkt.c:543:
```

Mine which works, the matching lines:
```
000c - <SPACES/NULS>
write to 0x8a52b50 [0x8a61b78] (139 bytes => 139 (0x8B))
0000 - 16 03 01 00 86 10 00 00-82 00 80 10 54 c2 a9 32   ............T..2
0010 - 4e 96 a8 4e d3 b8 ab bf-5d 81 a9 96 a1 8b f3 c5   N..N....].......
0020 - 6d 6d 2f 08 1e bc d9 db-d9 ed 1d 24 75 55 1e 09   mm/........$uU..
0030 - 39 ca 9e 3b f3 2c 31 a2-35 22 4b 14 50 12 76 69   9..;.,1.5"K.P.vi
0040 - 6d 5b a7 43 71 6d 3d 9e-6a c1 13 94 58 4b 6f 4d   m[0050 - 49 ec 34 2a e2 f7 ec 2a-6b 71 4b c5 02 cd fc f7   I.4*...*kqK.....
0060 - 87 44 1d 36 6c 03 44 43-2c 6e 88 85 9e 93 05 03   .D.6l.DC,n......
0070 - ff f1 17 22 c7 52 9c ba-09 50 1e 92 3c db f6 72   ...".R...P..<..r
0080 - af d7 1e e7 ac d7 1f 03-68 d6 72                  ........h.r
write to 0x8a52b50 [0x8a61b78](.Cqm=.j...XKoM) (6 bytes => 6 (0x6))
0000 - 14 03 01 00 01 01                                 ......
write to 0x8a52b50 [0x8a61b78] (53 bytes => 53 (0x35))
0000 - 16 03 01 00 30 97 e3 75-74 28 79 30 9f fd 30 67   ....0..ut(y0..0g
0010 - 7d 9b 17 53 ab 0f 00 9b-e8 5d 86 0b 1b 47 5a 30   }..S.....]...GZ0
0020 - e1 3f ab 10 3b 8c 8f b4-9a 4e 99 80 6b 35 74 0f   .?..;....N..k5t.
0030 - 4e 1d 1a 25 83                                    N..%.
read from 0x8a52b50 [0x8a580fb] (5 bytes => 5 (0x5))
0000 - 15 03 01 00 02                                    .....
read from 0x8a52b50 [0x8a58100] (2 bytes => 2 (0x2))
0000 - 02 28                                             .(
3077916872:error:14094410:SSL routines:SSL3_READ_BYTES:sslv3 alert handshake failure:s3_pkt.c:1256:SSL alert number 40
3077916872:error:1409E0E5:SSL routines:SSL3_WRITE_BYTES:ssl handshake failure:s3_pkt.c:596:
---
Certificate chain
 0 s:/serialNumber=MZ83tCxmiuTeAqw2Rl4wqWEKVw3P8ujt/C=US/ST=Massachusetts/L=Cambridge/O=Raytheon BBN Technologies/OU=GPO/CN=ch.geni.net
   i:/C=US/O=GeoTrust, Inc./CN=GeoTrust SSL CA
 1 s:/C=US/O=GeoTrust, Inc./CN=GeoTrust SSL CA
   i:/C=US/O=GeoTrust Inc./CN=GeoTrust Global CA
 2 s:/C=US/O=GeoTrust Inc./CN=GeoTrust Global CA
   i:/C=US/O=Equifax/OU=Equifax Secure Certificate Authority
...
```

Is it that alert 40?


_Trac comment by ahelsing on 12-18-2013 at 15:12_

**Comment by ahelsing** [comment]
alert 40 just means a handshake error.

This also fails for Vic. It worked for Niky from the same machine yesterday. She is not on the VPN.
So something about the apache config change is causing her problems.

Niky says it wasn't working for Vic from the BBN guest net. Then he VPNed in and it worked. Then from guest again it worked this time.

Niky gets the same error talking to port 8444, which has the same openssl_no_ca that we used before yesterday.

Her openssl version:
OpenSSL 0.9.8y 5 Feb 2013
Note that mine on ubuntu is: OpenSSL 1.0.1 14 Mar 2012

When Niky connects via T-Mobile from the same computer, it works.

So it isn't the computer per se. It must be something the BBN Guest net does or doesn't do?

Now that Niky has done it once, going back to BBN Guest net it seems to work again. stranger and stranger.


_Trac comment by ahelsing on 12-18-2013 at 15:27_

**Comment by ahelsing** [comment]
A few thoughts:
 - Does the Apache server cache the SSL session, such that when you connect successfully via a non-BBN guest connection, the full handshake doesn't have to happen on the BBN guest network - which is why it appears to suddenly work there again?
 - Test: Does it happen to everyone when on the BBN guest network? Sarah, how about you? Collect a few data points of using openssl to connect to ch.geni.net:8443 from different machines when on the BBN wireless and not on the VPN
 - Try to connect via openssl to www.google.com:443 - what does that look like when on the BBN guest net on a machine that fails connecting to ch.geni.net:8443, vs on a machine where it works. Same?
 - Consider setting up a GENI node with a public IP using an Apache config similar to that on ch.geni.net (see /etc/apache2/site-available/ch-ssl and the virtualHost for port 8443). Try the openssl test to that machine, to isolate out just the Apache config and see if it happens when it is not a BBN server
  - Be sure to use the same OS and version of Apache
  - If we try this, set the logging level (within that ch-ssl file) to debug to see if the server tells us more information about what is failing
 - Is there another BBN https server that we can try? IE does it work to other BBN servers, just not ch.geni.net?
 - At ch.geni.net, compare the openssl behavior going to ch.geni.net:8443 and ch.geni.net:8444 - same? different?
  - 8444 port does not require a valid client cert. So that is pretty similar to the config before the Wednesday upgrade, after which we noticed this failure. If it works at port 8444 then that suggests the Apache config is related
 - So for the tests do:
  - Use 1 machine where omni connects while on the BBN guest net, if it exists and 1 where it fails
  - Try the test on BBN guest and on the VPN to compare. Do BBN guest first
  - Try connecting to: ch.geni.net:8443, ch.geni.net:8444, some non BBN https server, some other BBN https server
  - Try with and without supplying the client certificate (the `-cert` and `-key` options)
 - Try the various openssl tests using these options:
```
openssl s_client -msg -prexit -state -debug
```
 - To pass a client certificate add these options:
```
-cert <path to cert file> -key <path to key file>
```
 

Another thing we could do would be to turn on debug logging in Apache on nye. It's a 1 line change to `/etc/apache2/sites-available/ch-ssl` in the port 8443 virtual host. But we should make the change, do our testing, and then change it back. Otherwise the logs will be ridiculous. And we should do it while the portal is in maintenance mode: That way we can still construct SSL sessions, but most users will be scared away and we'll get fewer connections filling up the logs.

And if we can't resolve this, then the minimal Apache config change we want to try: Change the SSLVerifyClient line for the port 8443 virtualHost from "require" to "optional". See if that works from BBN guest. If that still doesn't work, change "optional" to "optional_no_ca".

But realize we cannot live with either of those long term.


_Trac comment by ahelsing on 12-19-2013 at 08:45_

**Comment by ahelsing** [comment]
To answer the question above, I was able to use omni via the Guest network when debugging with Niky yesterday, but I may have had the VPN on.  Vic saw behavior that matched Niky.  

Also, I know it shouldn't matter, but I'm an operator. 

_Trac comment by sedwards (github user: seledwards) on 12-19-2013 at 10:54_

**Comment by ahelsing** [comment]
Today (Thurs) Niky got a similar SSL error using her travel laptop and a non-GENI application while sitting on the 5th floor but using BBNGuest. 

This implies the issue lies with the network.  Niky will followup with IDSG.

_Trac comment by sedwards (github user: seledwards) on 12-19-2013 at 16:56_

**Comment by ahelsing** [comment]
IDSG is handling this, which now appears to have to do with DNS.

_Trac comment by ahelsing on 01-07-2014 at 08:39_
