### ISSUE TITLE
geni-revoke-member-privilege results in authorization error

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-ch#21]
I have operator and lead privileges on my portal so I think I should be authorized to do anything.  When I tried to revoke a members lead privilege (using geni-revoke-member-privilege) I get the following amsoil stacktrace:

2013-11-08 15:06:57,601 [INFO] - [mav1] Called: <revoke_member_privilege>
2013-11-08 15:06:57,605 [ERROR] - [mav1] [AUTHORIZATION] AUTHORIZATION_ERROR (Caller not authorized to call method revoke_member_privilege with options {} arguments {'privilege': 'PROJECT_LEAD', 'member_uid': '2a\
14f82f-0ceb-429f-a4ce-e443c064ead4'} query ME.MAY_REVOKE_MEMBER_PRIVILEGE<-CALLER)
2013-11-08 15:06:57,605 [ERROR] - [mav1] Traceback (most recent call last):
  File "/usr/share/geni-ch/chapi/AMsoil/src/plugins/chapiv1rpc/chapi/MemberAuthority.py", line 451, in revoke_member_privilege
    'privilege': privilege})
  File "/usr/share/geni-ch/chapi/AMsoil/src/plugins/chrm/ABACGuard.py", line 223, in validate_call
    credentials, options, arguments)
  File "/usr/share/geni-ch/chapi/AMsoil/src/plugins/chrm/ABACGuard.py", line 66, in validate
    self.authorize_call(client_cert, method, credentials, options, arguments)
  File "/usr/share/geni-ch/chapi/AMsoil/src/plugins/chrm/ABACGuard.py", line 183, in authorize_call
    (method, options, arguments, query));
CHAPIv1AuthorizationError: [AUTHORIZATION] AUTHORIZATION_ERROR (Caller not authorized to call method revoke_member_privilege with options {} arguments {'privilege': 'PROJECT_LEAD', 'member_uid': '2a14f82f-0ceb-429f-a4ce-e443c064ead4'} query ME.MAY_REVOKE_MEMBER_PRIVILEGE<-CALLER)

 _Imported from trac ticket [#21](http://trac.gpolab.bbn.com/chapi/ticket/21),  created by phelinek on 11-08-2013 at 16:11, last modified: 11-19-2013 at 11:57_

**Comment by ahelsing** [comment]
I get the same errors when I run the command using the ma cert and key

_Trac comment by phelinek on 11-08-2013 at 16:14_

**Comment by ahelsing** [comment]
I do not get this error with add_member_privilege

_Trac comment by phelinek on 11-08-2013 at 16:36_

**Comment by MarshallBrinn** [comment]
Checked in a fix to this in MAv1Guard: The right policies should be 

```
	'revoke_member_privilege' :
            SubjectInvocationCheck([
                    "ME.MAY_REVOKE_MEMBER_PRIVILEGE<-ME.IS_AUTHORITY",
                    "ME.MAY_REVOKE_MEMBER_PRIVILEGE<-ME.IS_OPERATOR"
	            ], None, None),

```


_Trac comment by mbrinn (github user: MarshallBrinn) on 11-11-2013 at 16:01_
