### ISSUE TITLE
example-chapi.ini has incorrect paths, and INSTALL contains no directions for setting them

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-ch#28]
When i install CHAPI using the instructions in `chapi/INSTALL`, including copying /etc/geni-chapi/example-chapi.ini to chapi.ini and changing the settings recommended by INSTALL, AMsoil fails, logging:
```
[Mon Nov 11 17:48:24 2013] [warn] FastCGI: server "/usr/share/geni-ch/chapi/AMsoil/src/main.py" restarted (pid 5465)
Traceback (most recent call last):
  File "/usr/share/geni-ch/chapi/AMsoil/src/main.py", line 40, in <module>
    main()
  File "/usr/share/geni-ch/chapi/AMsoil/src/main.py", line 19, in main
    pm.init(config.PLUGINS_PATH)
  File "/usr/share/geni-ch/chapi/AMsoil/src/amsoil/core/pluginmanager.py", line 256, in init
    pluginInfo.setup()
  File "/usr/share/geni-ch/chapi/AMsoil/src/amsoil/core/pluginmanager.py", line 145, in setup
    self._pluginModule.setup()
  File "/usr/share/geni-ch/chapi/AMsoil/src/plugins/marm/plugin.py", line 35, in setup
    delegate = MAv1Implementation()
  File "/usr/share/geni-ch/chapi/AMsoil/src/plugins/marm/MAv1Implementation.py", line 171, in __init__
    for f in os.listdir(trusted_root) if not f.startswith('CAT')]
OSError: [Errno 2] No such file or directory: '/path/to/trusted/roots/directory'
```

Looks like my chapi.ini now contains a bunch of entries like:
```
; Folder which includes trusted clearinghouse certificates for GENI
;  API v3 (in .pem format). If relative path, the root is assumed to be
;  git repo root.
ch_cert_root=/path/to/trusted/roots/directory

; Location of CH certificate
ch_cert=/path/to/root/certificate.pem
```
etc.

 _Imported from trac ticket [#28](http://trac.gpolab.bbn.com/chapi/ticket/28),  created by chaos on 11-11-2013 at 17:53, last modified: 11-15-2013 at 08:11_

**Comment by tcmitchell** [comment]
The instructions in INSTALL have been clarified. All settings should be reviewed for accuracy in the local environment.

_Trac comment by tmitchel (github user: tcmitchell) on 11-12-2013 at 10:28_
