### ISSUE TITLE
lookup not robust to malformed call

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-ch#281]
If a caller provides options as a list or fails to provide the 'match' field in options, the MA produces ugly log messages:

```
04/18/2014 16:39:17:ERROR   :amsoil:[mav1] Call to known method <lookup> failed!
Traceback (most recent call last):
  File "/usr/share/geni-ch/chapi/AMsoil-gpo-0.3.2/src/plugins/flaskrpcs/xmlrpcdispatcher.py", line 49, in _dispatch
    return meth(*params)
TypeError: lookup() takes exactly 4 arguments (5 given)
04/18/2014 16:47:35:ERROR   :amsoil:[mav1] [SERVER] SERVER_ERROR ('list' object has no attribute 'has_key')
04/18/2014 16:47:35:ERROR   :amsoil:[mav1]   File "/usr/share/geni-ch/chapi/AMsoil-gpo-0.3.2/src/plugins/chapiv1rpc/chapi/MethodContext.py", line 164, in __enter__
    self._adjustIdentity()

  File "/usr/share/geni-ch/chapi/AMsoil-gpo-0.3.2/src/plugins/chapiv1rpc/chapi/MethodContext.py", line 125, in _adjustIdentity
    trusted_roots)

  File "/usr/share/geni-ch/chapi/AMsoil-gpo-0.3.2/src/plugins/chrm/ABACGuard.py", line 680, in adjust_client_identity
    trusted_roots)

  File "/usr/share/geni-ch/chapi/chapi/tools/SpeaksFor.py", line 62, in determine_speaks_for
    if options.has_key(OPTION_SPEAKING_FOR):

04/18/2014 16:47:35:INFO    :chapi:MA: hussam.nasir@uky.edu: Result from lookup_allowed_member_info: {'output': "[SERVER] SERVER_ERROR ('list' object has no attribute 'has_key')", 'code': 101, 'value': None}
04/18/2014 16:48:51:ERROR   :amsoil:[mav1] [SERVER] SERVER_ERROR ('list' object has no attribute 'has_key')
04/18/2014 16:48:51:ERROR   :amsoil:[mav1]   File "/usr/share/geni-ch/chapi/AMsoil-gpo-0.3.2/src/plugins/chapiv1rpc/chapi/MethodContext.py", line 164, in __enter__
    self._adjustIdentity()

  File "/usr/share/geni-ch/chapi/AMsoil-gpo-0.3.2/src/plugins/chapiv1rpc/chapi/MethodContext.py", line 125, in _adjustIdentity
    trusted_roots)

  File "/usr/share/geni-ch/chapi/AMsoil-gpo-0.3.2/src/plugins/chrm/ABACGuard.py", line 680, in adjust_client_identity
    trusted_roots)

  File "/usr/share/geni-ch/chapi/chapi/tools/SpeaksFor.py", line 62, in determine_speaks_for
    if options.has_key(OPTION_SPEAKING_FOR):

04/18/2014 16:48:51:INFO    :chapi:MA: hussam.nasir@uky.edu: Result from lookup_allowed_member_info: {'output': "[SERVER] SERVER_ERROR ('list' object has no attribute 'has_key')", 'code': 101, 'value': None}
04/18/2014 16:49:35:ERROR   :amsoil:[mav1] [SERVER] SERVER_ERROR (('match',))
04/18/2014 16:49:35:ERROR   :amsoil:[mav1]   File "/usr/share/geni-ch/chapi/AMsoil-gpo-0.3.2/src/plugins/chapiv1rpc/chapi/MemberAuthority.py", line 123, in lookup_allowed_member_info
    mc._session)

  File "/usr/share/geni-ch/chapi/AMsoil-gpo-0.3.2/src/plugins/marm/MAv1Implementation.py", line 380, in lookup_allowed_member_info
    public_options = {'match' : options['match'], 'filter' : public_fields}

04/18/2014 16:49:35:INFO    :chapi:MA: hussam.nasir@uky.edu: Result from lookup_allowed_member_info: {'output': "[SERVER] SERVER_ERROR (('match',))", 'code': 101, 'value': None}
04/18/2014 16:51:32:INFO    :chapi:SA: fabdulnavaz@uh.edu: Created slice etherpipe in project 4c7992fd-7643-444a-b7fc-330180204a90
04/18/2014 16:53:32:ERROR   :amsoil:[mav1] [SERVER] SERVER_ERROR (('match',))
04/18/2014 16:53:32:ERROR   :amsoil:[mav1]   File "/usr/share/geni-ch/chapi/AMsoil-gpo-0.3.2/src/plugins/chapiv1rpc/chapi/MemberAuthority.py", line 123, in lookup_allowed_member_info
    mc._session)

  File "/usr/share/geni-ch/chapi/AMsoil-gpo-0.3.2/src/plugins/marm/MAv1Implementation.py", line 380, in lookup_allowed_member_info
    public_options = {'match' : options['match'], 'filter' : public_fields}

04/18/2014 16:53:32:INFO    :chapi:MA: hussam.nasir@uky.edu: Result from lookup_allowed_member_info: {'output': "[SERVER] SERVER_ERROR (('match',))", 'code': 101, 'value': None}
```

 _Imported from trac ticket [#281](http://trac.gpolab.bbn.com/chapi/ticket/281),  created by ahelsing on 04-21-2014 at 11:15, last modified: 07-23-2014 at 13:35_

**Comment by ahelsing** [comment]
To test, use omni. Edit framework_chapi. About line 457 set options=[].
That reproduces the first error. I haven't managed to reproduce the second.


_Trac comment by ahelsing on 07-23-2014 at 12:42_

**Comment by ahelsing** [comment]
Added check in Method Context and MA lookup.


_Trac comment by ahelsing on 07-23-2014 at 13:35_
