### ISSUE TITLE
SQLAlchemy exceptions

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-ch#352]
Since the update to Ubuntu 12.04 I see in the chapi logs:
```
04/01/2015 13:41:54:INFO    :amsoil:[csv1] Called: <get_permissions>
04/01/2015 13:41:54:INFO    :chapi:CS: nriga@bbn.com: Invoked get_permissions Options {'_dummy': 'null'} Arguments {'principal': '762e2515-1b42-4474-9f87-6885e33724e6'}
04/01/2015 13:41:54:ERROR   :sqlalchemy.pool.NullPool:Exception during reset or similar
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/SQLAlchemy-1.0.0b4-py2.7-linux-i686.egg/sqlalchemy/pool.py", line 567, in _finalize_fairy
    fairy._reset(pool)
  File "/usr/local/lib/python2.7/dist-packages/SQLAlchemy-1.0.0b4-py2.7-linux-i686.egg/sqlalchemy/pool.py", line 701, in _reset
    pool._dialect.do_rollback(self)
  File "/usr/local/lib/python2.7/dist-packages/SQLAlchemy-1.0.0b4-py2.7-linux-i686.egg/sqlalchemy/engine/default.py", line 412, in do_rollback
    dbapi_connection.rollback()
ProgrammingError: SQLite objects created in a thread can only be used in that same thread.The object was created in thread id -1389384896 and this is thread id -1406170304
04/01/2015 13:41:54:ERROR   :sqlalchemy.pool.NullPool:Exception closing connection <sqlite3.Connection object at 0xb0ca2130>
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/SQLAlchemy-1.0.0b4-py2.7-linux-i686.egg/sqlalchemy/pool.py", line 251, in _close_connection
    self._dialect.do_close(connection)
  File "/usr/local/lib/python2.7/dist-packages/SQLAlchemy-1.0.0b4-py2.7-linux-i686.egg/sqlalchemy/engine/default.py", line 418, in do_close
    dbapi_connection.close()
ProgrammingError: SQLite objects created in a thread can only be used in that same thread.The object was created in thread id -1389384896 and this is thread id -1406170304
....
04/01/2015 13:41:54:INFO    :chapi:CS: nriga@bbn.com: Result from get_permissions: {'output': '', 'code': 0, 'value': [('project_use', '1', 'e2d9823c-296e-463c-aebd-0ac19ca203eb'), ('project_write', '1', 'e2d9823c-296e-463c-aebd-0ac19ca203eb'), ('project_read', '1', 'e2d9823c-296e-463c-aebd-0ac19ca203eb..
```

Niky was the user. She reports from her perspective she didn't see anything. There are 0 messages in the portal_error log at that time. So I suspect this is not experimenter visible.

Note the messages talk about sqlite.

Google search suggests one possible solution:
`connect_args={'check_same_thread':False},`

 _Imported from trac ticket [#352](http://trac.gpolab.bbn.com/chapi/ticket/352),  created by ahelsing on 04-02-2015 at 09:28, last modified: 04-09-2015 at 15:11_

**Comment by ahelsing** [comment]
With lots of reloading the home page, we reproduced this on cascade.

Using the mention of sqlite as a clue, we note that AMsoil uses SQLite - for the configdb among others. CHAPI does not. It's possible that Apache does as well.

SQLAlchemy with the upgrade went from 0.8+ to 1.0beta.

Chapi threads read that AMsoil configdb. But after server startup, no one writes to it.

Editing amconfigdb.py in AMsoil on cascade, and we could not reproduce the error. 
This makes sense if the problem is the multiple CHAPI threads all reading the same configdb and something doesn't like that. And the fix should be safe if no one is writing to that DB.

So the fix will be a patch on our local copy of AMsoil.


_Trac comment by ahelsing on 04-07-2015 at 16:44_

**Comment by ahelsing** [comment]
AMsoil tag gpo-0.3.3 contains this patch. This patch has been applied to the portals (illyrica, dagoola, marilac, casade, nye).

Error appears gone.

_Trac comment by ahelsing on 04-08-2015 at 10:54_

**Comment by tcmitchell** [comment]
Here is the actual fix:
```
diff --git a/src/vendor/configdb/amconfigdb.py b/src/vendor/configdb/amconfigdb.py
index f12faaa.10c96a6 100644
--- a/src/vendor/configdb/amconfigdb.py
+++ b/src/vendor/configdb/amconfigdb.py
@@ -14,7 +14,7 @@ import amsoil.core.log
 logger=amsoil.core.log.getLogger('configdb')
 
 # initialize sqlalchemy
-db_engine = create_engine(CONFIGDB_ENGINE, pool_recycle=6000) # please see the wiki for more info
+db_engine = create_engine(CONFIGDB_ENGINE, connect_args={'check_same_thread':False}, pool_recycle=6000) # please see the wiki for more info
 db_session_factory = sessionmaker(autoflush=True, bind=db_engine, expire_on_commit=False) # the class which can create sessions (factory pattern)
 db_session = scoped_session(db_session_factory) # still a session creator, but it will create _one_ session per thread and delegate all method calls to it
 # we could limit the session's scope (lifetime) to one request, but for this plugin this is not necessary
```


_Trac comment by tmitchel (github user: tcmitchell) on 04-08-2015 at 10:58_
