### ISSUE TITLE
Calling "update" with empty "fields" gives strange error

### ISSUE THREAD

**Issue by nbastin** [GENI-NSF/geni-ch#411]
Apparently this isn't legal (was hoping to trick it into not doing an update at all, but giving me all the project fields, but alas), but it just returns an internal exception to me instead of a nice error message:

```
{'code': 101,
 'output': '[SERVER] SERVER_ERROR ((psycopg2.ProgrammingError) syntax error at or near "WHERE"\nLINE 1: UPDATE pa_project SET  WHERE pa_project.project_name = \'VTSI...\n                               ^\n [SQL: \'UPDATE pa_project SET  WHERE pa_project.project_name = %(project_name_1)s\'] [parameters: {\'project_name_1\': \'VTSINJACKS\'}])',
 'value': None}
```

**Comment by ahelsing** [comment]
From server logs:
```
08/30/2015 19:52:18:ERROR   :amsoil:[sav1] Call to known method <update> failed!
Traceback (most recent call last):
  File "/usr/share/geni-ch/chapi/AMsoil-gpo-0.3.3/src/plugins/flaskrpcs/xmlrpcdispatcher.py", line 49, in _dispatch
    return meth(*params)
TypeError: update() takes exactly 5 arguments (4 given)
08/30/2015 19:53:36:ERROR   :amsoil:[sav1] [SERVER] SERVER_ERROR ((psycopg2.ProgrammingError) syntax error at or near "WHERE"
LINE 1: UPDATE pa_project SET  WHERE pa_project.project_name = 'VTSI...
                               ^
 [SQL: 'UPDATE pa_project SET  WHERE pa_project.project_name = %(project_name_1)s'] [parameters: {'project_name_1': 'VTSINJACKS'}])
08/30/2015 19:53:36:ERROR   :amsoil:[sav1]   File "/usr/share/geni-ch/chapi/AMsoil-gpo-0.3.3/src/plugins/chapiv1rpc/chapi/SliceAuthority.py", line 348, in update_project
    mc._session)

  File "/usr/share/geni-ch/chapi/AMsoil-gpo-0.3.3/src/plugins/sarm/SAv1PersistentImplementation.py", line 834, in update_project
    q = q.update(updates)
...
08/30/2015 19:53:36:INFO    :chapi:SA: nick.bastin@gmail.com: Result from update_project: {'output': '[SERVER] SERVER_ERROR ((psycopg2.ProgrammingError) syntax error at or near "WHERE"\nLINE 1: UPDATE pa_project SET  WHERE pa_project.project_name = \'VTSI...\n                               ^\n [SQL: \'UPDATE pa...
```
