### ISSUE TITLE
SSL error on portal login

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-ch#48]
I needed to log in as another member to give myself back lead role on a project.  When I logged in as Tom, I got the server error (below).  However, I was still able to see projects, edit membership,etc

2013-11-15 11:26:23,761 [ERROR] - [csv1] [SERVER] SERVER_ERROR ((ProgrammingError) SSL error: block type is not 01
 'SELECT cs_action.name AS cs_action_name, cs_action.context_type AS cs_action_context_type, sa_slice_member.slice_id AS context \nFROM cs_acti\
on, sa_slice_member, cs_policy \nWHERE sa_slice_member.member_id = %(member_id_1)s AND sa_slice_member.role = cs_policy.attribute AND cs_action\
.privilege = cs_policy.privilege AND cs_policy.context_type = %(context_type_1)s AND cs_action.context_type = cs_policy.context_type' {'member_\
id_1': '2a14f82f-0ceb-429f-a4ce-e443c064ead4', 'context_type_1': 2})
2013-11-15 11:26:23,761 [ERROR] - [csv1] Traceback (most recent call last):
  File "/usr/share/geni-ch/chapi/AMsoil/src/plugins/csrm/CredentialStore.py", line 92, in get_permissions
    credentials, options)
  File "/usr/share/geni-ch/chapi/AMsoil/src/plugins/csrm/CredentialStore.py", line 192, in get_permissions
    slice_rows = q.all()
  File "/usr/local/lib/python2.6/dist-packages/SQLAlchemy-0.8.2-py2.6-linux-i686.egg/sqlalchemy/orm/query.py", line 2237, in all
    return list(self)
  File "/usr/local/lib/python2.6/dist-packages/SQLAlchemy-0.8.2-py2.6-linux-i686.egg/sqlalchemy/orm/query.py", line 2349, in __iter__
    return self._execute_and_instances(context)
  File "/usr/local/lib/python2.6/dist-packages/SQLAlchemy-0.8.2-py2.6-linux-i686.egg/sqlalchemy/orm/query.py", line 2364, in _execute_and_insta\
nces
    result = conn.execute(querycontext.statement, self._params)
  File "/usr/local/lib/python2.6/dist-packages/SQLAlchemy-0.8.2-py2.6-linux-i686.egg/sqlalchemy/engine/base.py", line 662, in execute
    params)
  File "/usr/local/lib/python2.6/dist-packages/SQLAlchemy-0.8.2-py2.6-linux-i686.egg/sqlalchemy/engine/base.py", line 761, in _execute_clauseel\
ement
    compiled_sql, distilled_params
  File "/usr/local/lib/python2.6/dist-packages/SQLAlchemy-0.8.2-py2.6-linux-i686.egg/sqlalchemy/engine/base.py", line 874, in _execute_context
    context)
  File "/usr/local/lib/python2.6/dist-packages/SQLAlchemy-0.8.2-py2.6-linux-i686.egg/sqlalchemy/engine/base.py", line 1024, in _handle_dbapi_ex\
ception
    exc_info
  File "/usr/local/lib/python2.6/dist-packages/SQLAlchemy-0.8.2-py2.6-linux-i686.egg/sqlalchemy/util/compat.py", line 195, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/usr/local/lib/python2.6/dist-packages/SQLAlchemy-0.8.2-py2.6-linux-i686.egg/sqlalchemy/engine/base.py", line 867, in _execute_context
    context)
  File "/usr/local/lib/python2.6/dist-packages/SQLAlchemy-0.8.2-py2.6-linux-i686.egg/sqlalchemy/engine/default.py", line 324, in do_execute
    cursor.execute(statement, parameters)
ProgrammingError: (ProgrammingError) SSL error: block type is not 01
 'SELECT cs_action.name AS cs_action_name, cs_action.context_type AS cs_action_context_type, sa_slice_member.slice_id AS context \nFROM cs_acti\
on, sa_slice_member, cs_policy \nWHERE sa_slice_member.member_id = %(member_id_1)s AND sa_slice_member.role = cs_policy.attribute AND cs_action\
.privilege = cs_policy.privilege AND cs_policy.context_type = %(context_type_1)s AND cs_action.context_type = cs_policy.context_type' {'member_\
id_1': '2a14f82f-0ceb-429f-a4ce-e443c064ead4', 'context_type_1': 2}

 _Imported from trac ticket [#48](http://trac.gpolab.bbn.com/chapi/ticket/48),  created by phelinek on 11-15-2013 at 11:33, last modified: 12-16-2013 at 16:48_

**Comment by ahelsing** [comment]
we haven't reproduced this in a couple days

_Trac comment by ahelsing on 12-03-2013 at 15:09_

**Comment by ahelsing** [comment]
I saw the error trying to delete resources. Then I saw a variation trying to load the slice page:
```
ProgrammingError: (ProgrammingError) SSL error: padding check failed
 'SELECT cs_action.name AS cs_action_name, cs_action.context_type AS cs_action_context_type, sa_slice_member.slice_id AS context \nF
```


_Trac comment by ahelsing on 12-05-2013 at 15:05_

**Comment by ahelsing** [comment]
postgres DB logs for things like this:
```
2013-12-05 21:20:04 EST LOG:  could not send data to client: Broken pipe
2013-12-05 21:20:04 EST STATEMENT:  SELECT cs_action.name AS cs_action_name, cs_action.context_type AS cs_action_context_type, sa_slice_member.slice_id AS context
    FROM cs_action, sa_slice_member, cs_policy
    WHERE sa_slice_member.member_id = E'762e2515-1b42-4474-9f87-6885e33724e6' AND sa_slice_member.role = cs_policy.attribute AND cs_action.privilege = cs_policy.privilege AND cs_policy.context_type = 2 AND cs_action.context_type = cs_policy.context_type
2013-12-05 21:20:04 EST LOG:  SSL error: bad write retry
2013-12-05 21:20:04 EST LOG:  could not send data to client: Connection reset by peer
2013-12-05 21:20:04 EST LOG:  could not receive data from client: Connection reset by peer
2013-12-05 21:20:04 EST LOG:  unexpected EOF on client connection
```


_Trac comment by ahelsing on 12-05-2013 at 21:33_

**Comment by ahelsing** [comment]
We changed the postgres DB configuration on Friday to not use SSL, and have not seen this since.

We should still clean up session handling.


_Trac comment by ahelsing on 12-09-2013 at 09:35_

**Comment by ahelsing** [comment]
Still not seeing this.
SSL session handling cleanup is now in.


_Trac comment by ahelsing on 12-16-2013 at 16:48_
