### ISSUE TITLE
error when changing member roles in the portal

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-ch#49]
I am now able to swap lead and admin roles using the scripts, but when I tried to do it in the portal (I'm lead and Tom is admin, and I tried to switch them), I get a  server error (below).  Looks like it is using urn and it expects uuid.  

2013-11-15 14:40:30,650 [ERROR] - [sav1] [SERVER] SERVER_ERROR ((DataError) invalid input syntax for uuid: "urn:publicid:IDN+ch-ph.gpolab.bbn.c\
om+user+tmitchel"
LINE 3: WHERE ma_member_attribute.member_id = E'urn:publicid:IDN+ch-...
                                              ^
 'SELECT ma_member_attribute.value AS ma_member_attribute_value \nFROM ma_member_attribute \nWHERE ma_member_attribute.member_id = %(member_id_\
1)s AND ma_member_attribute.name = %(name_1)s' {'name_1': 'PROJECT_LEAD', 'member_id_1': 'urn:publicid:IDN+ch-ph.gpolab.bbn.com+user+tmitchel'}\
)
2013-11-15 14:40:30,651 [ERROR] - [sav1] Traceback (most recent call last):
  File "/usr/share/geni-ch/chapi/AMsoil/src/plugins/chapiv1rpc/chapi/SliceAuthority.py", line 426, in modify_project_membership
    credentials, options)
  File "/usr/share/geni-ch/chapi/AMsoil/src/plugins/sarm/SAv1PersistentImplementation.py", line 782, in modify_project_membership
    rows = q.all()
  File "/usr/local/lib/python2.6/dist-packages/SQLAlchemy-0.8.2-py2.6-linux-i686.egg/sqlalchemy/orm/query.py", line 2237, in all
    return list(self)
  File "/usr/local/lib/python2.6/dist-packages/SQLAlchemy-0.8.2-py2.6-linux-i686.egg/sqlalchemy/orm/query.py", line 2349, in __iter__
    return self._execute_and_instances(context)
  File "/usr/local/lib/python2.6/dist-packages/SQLAlchemy-0.8.2-py2.6-linux-i686.egg/sqlalchemy/orm/query.py", line 2364, in _execute_and_insta\
nces
    result = conn.execute(querycontext.statement, self._params)
  File "/usr/local/lib/python2.6/dist-packages/SQLAlchemy-0.8.2-py2.6-linux-i686.egg/sqlalchemy/engine/base.py", line 662, in execute
    params)
  File "/usr/local/lib/python2.6/dist-packages/SQLAlchemy-0.8.2-py2.6-linux-i686.egg/sqlalchemy/engine/base.py", line 761, in _execute_clauseel\
ement
    compiled_sql, distilled_params
  File "/usr/local/lib/python2.6/dist-packages/SQLAlchemy-0.8.2-py2.6-linux-i686.egg/sqlalchemy/engine/base.py", line 874, in _execute_context
    context)
  File "/usr/local/lib/python2.6/dist-packages/SQLAlchemy-0.8.2-py2.6-linux-i686.egg/sqlalchemy/engine/base.py", line 1024, in _handle_dbapi_ex\
ception
    exc_info
  File "/usr/local/lib/python2.6/dist-packages/SQLAlchemy-0.8.2-py2.6-linux-i686.egg/sqlalchemy/util/compat.py", line 195, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/usr/local/lib/python2.6/dist-packages/SQLAlchemy-0.8.2-py2.6-linux-i686.egg/sqlalchemy/engine/base.py", line 867, in _execute_context
    context)
  File "/usr/local/lib/python2.6/dist-packages/SQLAlchemy-0.8.2-py2.6-linux-i686.egg/sqlalchemy/engine/default.py", line 324, in do_execute
    cursor.execute(statement, parameters)
DataError: (DataError) invalid input syntax for uuid: "urn:publicid:IDN+ch-ph.gpolab.bbn.com+user+tmitchel"
LINE 3: WHERE ma_member_attribute.member_id = E'urn:publicid:IDN+ch-...
                                              ^
 'SELECT ma_member_attribute.value AS ma_member_attribute_value \nFROM ma_member_attribute \nWHERE ma_member_attribute.member_id = %(member_id_\
1)s AND ma_member_attribute.name = %(name_1)s' {'name_1': 'PROJECT_LEAD', 'member_id_1': 'urn:publicid:IDN+ch-ph.gpolab.bbn.com+user+tmitchel'}

 _Imported from trac ticket [#49](http://trac.gpolab.bbn.com/chapi/ticket/49),  created by phelinek on 11-15-2013 at 14:44, last modified: 11-19-2013 at 11:59_

**Comment by ahelsing** [comment]
minor bug fix - use uid, fixed along with implementation of tkt29

_Trac comment by phelinek on 11-18-2013 at 17:56_
