### ISSUE TITLE
enable/disable user scripts fail

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-ch#98]
Trying to enable or disable a user fails:

```
12/02/2013 13:32:17:ERROR   :chapi:MA: ahelsing@geni.net: Exception: '_GENI_MEMBER_ENABLED'
  File "/usr/share/geni-ch/chapi/AMsoil-gpo-0.3.2/src/plugins/chapiv1rpc/chapi/MemberAuthority.py", line 418, in enable_user
    options)
  File "/usr/share/geni-ch/chapi/AMsoil-gpo-0.3.2/src/plugins/marm/MAv1Implementation.py", line 923, in enable_user
    self.update_attr(session, '_GENI_MEMBER_ENABLED', enabled_str, member_id, 'f')
  File "/usr/share/geni-ch/chapi/AMsoil-gpo-0.3.2/src/plugins/marm/MAv1Implementation.py", line 387, in update_attr
    if len(self.get_attr_for_uid(session, attr, uid)) > 0:
  File "/usr/share/geni-ch/chapi/AMsoil-gpo-0.3.2/src/plugins/marm/MAv1Implementation.py", line 232, in get_attr_for_uid
    q = q.filter(MemberAttribute.name == MA.field_mapping[attr])

12/02/2013 13:32:17:ERROR   :amsoil:[mav1] [SERVER] SERVER_ERROR ('_GENI_MEMBER_ENABLED')
12/02/2013 13:32:17:ERROR   :amsoil:[mav1] Traceback (most recent call last):
  File "/usr/share/geni-ch/chapi/AMsoil-gpo-0.3.2/src/plugins/chapiv1rpc/chapi/MemberAuthority.py", line 418, in enable_user
    options)
  File "/usr/share/geni-ch/chapi/AMsoil-gpo-0.3.2/src/plugins/marm/MAv1Implementation.py", line 923, in enable_user
    self.update_attr(session, '_GENI_MEMBER_ENABLED', enabled_str, member_id, 'f')
  File "/usr/share/geni-ch/chapi/AMsoil-gpo-0.3.2/src/plugins/marm/MAv1Implementation.py", line 387, in update_attr
    if len(self.get_attr_for_uid(session, attr, uid)) > 0:
  File "/usr/share/geni-ch/chapi/AMsoil-gpo-0.3.2/src/plugins/marm/MAv1Implementation.py", line 232, in get_attr_for_uid
    q = q.filter(MemberAttribute.name == MA.field_mapping[attr])
KeyError: '_GENI_MEMBER_ENABLED'
```

 _Imported from trac ticket [#98](http://trac.gpolab.bbn.com/chapi/ticket/98),  created by ahelsing on 12-02-2013 at 13:33, last modified: 12-02-2013 at 13:59_

**Comment by ahelsing** [comment]
I suspect something is just missing from MA_constants. There is even a related 'TODO' item in that file.

_Trac comment by ahelsing on 12-02-2013 at 13:34_
